services:
  traefik: # reverse proxy
    image: "traefik:3.1"
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=10000"
      - "--accesslog.fields.defaultMode=keep"
      - "--accesslog.fields.headers.defaultMode=keep"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=info@myemail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"

    networks:
      - traefik-net

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./logs:/logs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


networks:
  traefik-net:
    name: traefik-net # removes dir prefix