apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
            prospector:
             scanner:
               fingerprint.enabled: true
               symlinks: true
            file_identity.fingerprint: ~

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    
    output.logstash:
      hosts: '${LOGSTASH_URL}'
      ssl.enabled: true
    #  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
    #  ssl.certificate: "/usr/share/filebeat/certs/client.crt"
    #  ssl.key: "/usr/share/filebeat/certs/client.key"
